// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTrackingSystem.Infrastructure.Persistence;

#nullable disable

namespace TaskTrackingSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218110740_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Sprints", t =>
                        {
                            t.HasCheckConstraint("CK_Sprint_EndDate", "[EndDate] > [StartDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 16, 15, 39, 44, 0, DateTimeKind.Utc),
                            Name = "Sprint 1",
                            StartDate = new DateTime(2026, 2, 16, 15, 39, 44, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint 2",
                            StartDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Nova 1",
                            StartDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Nova 2",
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Nova 3",
                            StartDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Nova 4",
                            StartDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Titan 1",
                            StartDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Titan 2",
                            StartDate = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Falcon 1",
                            StartDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Falcon 2",
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprint Falcon 3",
                            StartDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.SprintTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            AssigneeId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Description = "payments",
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            Status = "InProgress",
                            Title = "Integrate payments"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000002"),
                            AssigneeId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000002"),
                            Status = "ToDo",
                            Title = "Basket implementation"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Description = "ETL pipeline description",
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            Status = "InProgress",
                            Title = "Design ETL pipeline"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            Status = "Done",
                            Title = "Ingest raw event data"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            Status = "ToDo",
                            Title = "Write data quality checks"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            Status = "ToDo",
                            Title = "Build reporting schema"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000067"),
                            AssigneeId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            Status = "ToDo",
                            Title = "Implement CI-CD"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "ToDo",
                            Title = "Create sales dashboard"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "InProgress",
                            Title = "Implement funnel analysis"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "Done",
                            Title = "Build cohort report"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "InProgress",
                            Title = "Optimize slow queries"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "ToDo",
                            Title = "Add revenue metrics"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "Done",
                            Title = "Set up dbt models"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000013"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "InProgress",
                            Title = "Document pipeline architecture"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000014"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            Status = "ToDo",
                            Title = "Write data dictionary"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000015"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "InProgress",
                            Title = "Train churn prediction model"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000016"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "ToDo",
                            Title = "Evaluate model metrics"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000017"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "Done",
                            Title = "Set up MLflow tracking"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000018"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "ToDo",
                            Title = "Feature engineering for LTV"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000019"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "InProgress",
                            Title = "Build prediction API"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000020"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "Done",
                            Title = "Write model card"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000021"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            Status = "ToDo",
                            Title = "A/B test framework setup"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000022"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "ToDo",
                            Title = "Deploy model to production"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "InProgress",
                            Title = "Monitor model drift"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000024"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "InProgress",
                            Title = "Update stakeholder report"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000025"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "ToDo",
                            Title = "Retrain pipeline automation"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000026"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "Done",
                            Title = "Build alerting for predictions"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000027"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "Done",
                            Title = "Archive old experiments"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000028"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "InProgress",
                            Title = "Load test prediction API"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000029"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "Done",
                            Title = "Migrate feature store"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000030"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "ToDo",
                            Title = "Review data retention policy"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000031"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            Status = "ToDo",
                            Title = "Document model endpoints"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000032"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            Status = "Done",
                            Title = "Set up Kubernetes cluster"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000033"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            Status = "InProgress",
                            Title = "Configure Helm charts"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000034"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            Status = "Done",
                            Title = "Set up CI/CD pipeline"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000035"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            Status = "ToDo",
                            Title = "Implement secret management"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000036"),
                            AssigneeId = new Guid("b0000001-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            Status = "InProgress",
                            Title = "Write infrastructure docs"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000037"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            Status = "Done",
                            Title = "Configure load balancer"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000038"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "InProgress",
                            Title = "Set up monitoring with Grafana"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000039"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "ToDo",
                            Title = "Configure alerting rules"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000040"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "Done",
                            Title = "Migrate to Docker Compose v2"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000041"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "ToDo",
                            Title = "Automate DB backups"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000042"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "InProgress",
                            Title = "Audit IAM permissions"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000043"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "Done",
                            Title = "Update Terraform modules"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000044"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "ToDo",
                            Title = "Add health check endpoints"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000045"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "InProgress",
                            Title = "Set up staging environment"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000046"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            Status = "ToDo",
                            Title = "Implement log aggregation"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000047"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000009"),
                            Status = "InProgress",
                            Title = "Design landing page mockup"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000048"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000009"),
                            Status = "Done",
                            Title = "Set up Tailwind CSS config"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000049"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000009"),
                            Status = "InProgress",
                            Title = "Build navigation component"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000050"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000009"),
                            Status = "ToDo",
                            Title = "Implement dark mode toggle"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000051"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000009"),
                            Status = "ToDo",
                            Title = "Write component unit tests"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000052"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "InProgress",
                            Title = "Refactor button library"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000053"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "ToDo",
                            Title = "Add form validation"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000054"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "Done",
                            Title = "Implement toast notifications"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000055"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "InProgress",
                            Title = "Fix mobile layout bugs"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000056"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "ToDo",
                            Title = "Create storybook stories"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000057"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "ToDo",
                            Title = "Update design tokens"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000058"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            Status = "Done",
                            Title = "Accessibility audit"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000059"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "ToDo",
                            Title = "Build data table component"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000060"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "InProgress",
                            Title = "Integrate chart library"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000061"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "Done",
                            Title = "Implement pagination"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000062"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "InProgress",
                            Title = "Write E2E tests for dashboard"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000063"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "ToDo",
                            Title = "Add export to CSV feature"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000064"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "ToDo",
                            Title = "Performance profiling"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000065"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "Done",
                            Title = "Fix Safari rendering issues"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000066"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            SprintId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            Status = "InProgress",
                            Title = "Add skeleton loaders"
                        });
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Description = "Responsible for data pipelines, reporting, and ML experiments",
                            Name = "Data & Analytics"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Description = "main team",
                            Name = "Main team"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Description = "Handles infrastructure, CI/CD pipelines, and cloud architecture",
                            Name = "Platform Engineering"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Description = "Owns all UI/UX development and design system work",
                            Name = "Frontend Guild"
                        });
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "U",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "olivia.reyes@mailhub.net",
                            FirstName = "Olivia",
                            LastName = "Reyes",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "jake.morrison@codehaus.dev",
                            FirstName = "Jake",
                            LastName = "Morrison",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "grace.lindqvist@nordic.dev",
                            FirstName = "Grace",
                            LastName = "Lindqvist",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "paul.nakamura@devmail.jp",
                            FirstName = "Paul",
                            LastName = "Nakamura",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "rosa.andersen@scandev.net",
                            FirstName = "Rosa",
                            LastName = "Andersen",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "brian.kowalski@techcorp.net",
                            FirstName = "Brian",
                            LastName = "Kowalski",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "felix.romero@webdev.co",
                            FirstName = "Felix",
                            LastName = "Romero",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "elena.okonkwo@fastmail.io",
                            FirstName = "Elena",
                            LastName = "Okonkwo",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "kira.bellamy@devzone.io",
                            FirstName = "Kira",
                            LastName = "Bellamy",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000013"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "iris.castillo@latintech.net",
                            FirstName = "Iris",
                            LastName = "Castillo",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member",
                            TeamId = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000014"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "clara.nguyen@outlook.dev",
                            FirstName = "Clara",
                            LastName = "Nguyen",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000015"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "derek.patel@mailbox.org",
                            FirstName = "Derek",
                            LastName = "Patel",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000016"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "sam.kofi@ghanatech.io",
                            FirstName = "Sam",
                            LastName = "Kofi",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000017"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "henry.yamamoto@jptech.io",
                            FirstName = "Henry",
                            LastName = "Yamamoto",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000018"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "alice.hartman@devmail.io",
                            FirstName = "Alice",
                            LastName = "Hartman",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000019"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "nolan.bergstrom@nordic.io",
                            FirstName = "Nolan",
                            LastName = "Bergstrom",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000020"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "tara.voss@eurohub.dev",
                            FirstName = "Tara",
                            LastName = "Voss",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000021"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "quinn.fitzgerald@irishtech.io",
                            FirstName = "Quinn",
                            LastName = "Fitzgerald",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000022"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "maya.thornton@cloudmail.dev",
                            FirstName = "Maya",
                            LastName = "Thornton",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTime(2026, 2, 17, 21, 52, 0, 0, DateTimeKind.Utc),
                            Email = "liam.osei@afritech.co",
                            FirstName = "Liam",
                            LastName = "Osei",
                            PasswordHash = "$2a$11$O1xLiQXLjHihe82/tilSR.G0/rF87lIT/vAziJ8qU5KEpUftJKFoW",
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("TaskTrackingSystem.Domain.Entities.Team", "Team")
                        .WithMany("Sprints")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.SprintTask", b =>
                {
                    b.HasOne("TaskTrackingSystem.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskTrackingSystem.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaskTrackingSystem.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Tasks")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("TaskTrackingSystem.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("TaskTrackingSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
